import {Arma} from "./arma";

export interface Personagem {
  id?: number,
  nome?: string,
  origem?: string,
  arquetipo?: string,
  profissao?: string,
  nivel?: number,
  residencia?: string,
  personalidade?: string,
  motivacao?: string,
  idade?: number,
  sexo?: string,
  peso?: number,
  altura?: number,
  corpo?: number,
  agilidade?: number,
  astucia?: number,
  presenca?: number,
  fortitude?: number,
  reflexos?: number,
  iniciativa?: number,
  vontade?: number,
  experiencia?: number,
  defesa?: number,
  stress?: number,
  saude?: number,
  vigor?: number,
  proficiencia?: number,
  determinacao?: number,
  moralidade?: number,
  conhecimentos?: string,
  equipamento?: string,
  municaoTotal?: number,
  dinheiro?: number,
  ouro?: number,
  cargaLeve?: number,
  cargaMedia?: number,
  cargaPesada?: number,
  cargaMaxima?: number,
  armas?: Arma[]
}
